name: "prep-terraform"
description: "Configures Terraform environment"
inputs:
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  tf-workspace:
    description: "Terraform workspace"
    required: true
  tf-version:
    description: "Terraform version"
    required: true
    default: "1.2.5"
runs:
  using: "composite"
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: false
    - name: "Configure AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Terraform init
      shell: bash
      run: |
        terraform init
        terraform workspace select ${{ inputs.tf-workspace }}
